development:
  adapter: postgresql
  encoding: unicode
  database: googleanalytics_development
  pool: 5
  host: localhost
  username: postgres
  password: gado595
  

production:
  adapter: postgresql
  encoding: unicode
  database: googleanalytics_production
  pool: 5
  host: localhost
  username: postgres
  password: gado595